ALTER TABLE SH.CUSTOMERS
MODIFY CUST_GENDER CHAR(1) NULL
/

ALTER TABLE SH.CUSTOMERS
ADD SCHEMA_VERSION NUMBER(1,0) DEFAULT 1 NOT NULL
/

CREATE OR REPLACE TRIGGER SH.CUSTOMERS_NOT_NULL_TRIGGER
BEFORE INSERT ON SH.CUSTOMERS
FOR EACH ROW
BEGIN
    IF :NEW.SCHEMA_VERSION = 1 AND :NEW.CUST_GENDER IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'CUST_GENDER cannot be null for schema version 1');
    END IF;
END;
/