insert into CONSTRAINT_ON_NEW_SCHEMA.BASE_TABLE
    (PRIMARY_KEY, TO_BE_UNIQUE, TO_BE_CHECKED_ON_STATIC,
     TO_BE_CHECKED_ON_OTHER_FIELD, SOON_TO_BE_CEILER, TO_BE_DEFAULT,
     TO_BE_NOT_NULL)
values (1, 1, 7, 14, 50, 'NOT DEFAULT', 'NOT NULL');

insert into CONSTRAINT_ON_NEW_SCHEMA.BASE_TABLE
    (PRIMARY_KEY, TO_BE_UNIQUE, TO_BE_CHECKED_ON_STATIC,
     TO_BE_CHECKED_ON_OTHER_FIELD, SOON_TO_BE_CEILER, TO_BE_DEFAULT,
     TO_BE_NOT_NULL)
values (2, 1, -8, 74, 30, 'NOT DEFAULT ERROR EXAMPLE', null);

insert into CONSTRAINT_ON_NEW_SCHEMA.BASE_TABLE
    (PRIMARY_KEY, TO_BE_UNIQUE, TO_BE_CHECKED_ON_STATIC,
     TO_BE_CHECKED_ON_OTHER_FIELD, SOON_TO_BE_CEILER, TO_BE_DEFAULT,
     TO_BE_NOT_NULL)
values (3, 2, 44, 52, 20, 'NOT DEFAULT ERROR EXAMPLE', null);

commit;