alter table SH.CUSTOMERS add SCHEMA_VERSION NUMBER(1,0) default 2
/

UPDATE SH.CUSTOMERS
SET SCHEMA_VERSION = 1
WHERE 1 = 1
/

ALTER TABLE SH.CUSTOMERS ADD CUST_FULL_NAME VARCHAR2(100 CHAR)
/

CREATE OR REPLACE TRIGGER SH.CUSTOMERS_UPDATE_SCHEMA_VERSION_TGR
BEFORE INSERT ON SH.CUSTOMERS
FOR EACH ROW
BEGIN
    IF ( (:NEW.CUST_FIRST_NAME IS NOT NULL AND :NEW.CUST_LAST_NAME IS NOT NULL) AND :NEW.CUST_FULL_NAME IS NULL )
    THEN
        :NEW.SCHEMA_VERSION := 1;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER SH.CUSTOMERS_MERGE_NAME_AUTOMATICALLY_TGR
BEFORE INSERT ON SH.CUSTOMERS
FOR EACH ROW
BEGIN
    IF ( :NEW.CUST_FIRST_NAME IS NOT NULL AND (:NEW.SCHEMA_VERSION = 1 OR :NEW.SCHEMA_VERSION IS NULL) ) AND :NEW.CUST_FULL_NAME IS NULL
    THEN
        :NEW.CUST_FULL_NAME := :NEW.CUST_FIRST_NAME || ' ' || :NEW.CUST_LAST_NAME;
    END IF;
END;
/