CREATE SEQUENCE SH.PRODUCTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE
/

UPDATE SH.PRODUCTS
SET PROD_NAME = PROD_NAME || '_' || PRODUCTS_SEQ.NEXTVAL
WHERE SCHEMA_VERSION = 1
/

ALTER TABLE SH.PRODUCTS
ADD CONSTRAINT UNIQUE_PROD_NAME UNIQUE (PROD_NAME)
/

ALTER TABLE SH.PRODUCTS
DROP COLUMN SCHEMA_VERSION
/

DROP TRIGGER UNIQUE_ON_PRODUCTS_TGR
/

DROP SEQUENCE SH.PRODUCTS_SEQ