UPDATE SH.CUSTOMERS
SET CUST_MARITAL_STATUS = 'unknown'
WHERE CUST_MARITAL_STATUS IS NULL
/

ALTER TABLE SH.CUSTOMERS 
MODIFY CUST_MARITAL_STATUS VARCHAR2(20) NOT NULL

/

DROP TRIGGER CUST_MARITAL_STATUS_NOT_NULL_TGR
/