ALTER TABLE SH.CUSTOMERS
ADD SCHEMA_VERSION NUMBER(1,0) DEFAULT 2 NOT NULL
/

CREATE OR REPLACE TRIGGER CUST_MARITAL_STATUS_NOT_NULL_TGR
BEFORE INSERT
ON SH.CUSTOMERS
FOR EACH ROW
BEGIN
    IF :NEW.SCHEMA_VERSION = 2 AND :NEW.CUST_MARITAL_STATUS IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'CUST_MARITAL_STATUS cannot be NULL for SCHEMA_VERSION 2');
    END IF;
END;