UPDATE SH.CUSTOMERS
SET CUSTOMER_CONTACT = customer_contact_type(cust_main_phone_number, cust_email)
WHERE SCHEMA_VERSION = 1
/

ALTER TABLE SH.CUSTOMERS
DROP COLUMN cust_main_phone_number
/

ALTER TABLE SH.CUSTOMERS
DROP COLUMN cust_email
/

ALTER TABLE SH.CUSTOMERS
DROP COLUMN SCHEMA_VERSION
/

DROP TRIGGER SH.CUSTOMERS_CONTACT_TRG
/