ALTER TABLE SH.CUSTOMERS
ADD SCHEMA_VERSION NUMBER(1,0) DEFAULT 1 NOT NULL
/

ALTER TABLE SH.CUSTOMERS
ADD CUST_INCOME_LEVEL_LETTER VARCHAR2(1)
/

ALTER TABLE SH.CUSTOMERS
ADD CUST_INCOME_LEVEL_RANGE VARCHAR2(20)
/

CREATE OR REPLACE TRIGGER SH.CUSTOMERS_DIVIDE_INCOME_LEVEL
BEFORE INSERT
ON SH.CUSTOMERS
FOR EACH ROW
DECLARE
		delimiter_position NUMBER;
BEGIN
    IF :NEW.CUST_INCOME_LEVEL IS NOT NULL AND :NEW.SCHEMA_VERSION = 1 THEN
        delimiter_position := instr(:NEW.CUST_INCOME_LEVEL, ':');
        IF delimiter_position > 0 THEN
            :NEW.CUST_INCOME_LEVEL_LETTER := substr(:NEW.CUST_INCOME_LEVEL, 1, delimiter_position-1);
            :NEW.CUST_INCOME_LEVEL_RANGE := substr(:NEW.CUST_INCOME_LEVEL, delimiter_position+2);
        END IF;
    END IF;
END;
/