UPDATE SH.CUSTOMERS
SET CUST_INCOME_LEVEL_LETTER = substr(CUST_INCOME_LEVEL, 1, instr(CUST_INCOME_LEVEL, ':')-1),
    CUST_INCOME_LEVEL_RANGE = substr(CUST_INCOME_LEVEL, instr(CUST_INCOME_LEVEL, ':')+2)
WHERE CUST_INCOME_LEVEL IS NOT NULL AND SCHEMA_VERSION = 1
/

ALTER TABLE SH.CUSTOMERS
DROP COLUMN CUST_INCOME_LEVEL
/

ALTER TABLE SH.CUSTOMERS
DROP COLUMN SCHEMA_VERSION
/

DROP TRIGGER SH.CUSTOMERS_DIVIDE_INCOME_LEVEL
/