insert into CONSTRAINT_ON_OLD_SCHEMA.BASE_TABLE(
        PRIMARY_KEY, UNIQUE_CONSTRAINT,
        CHECK_ON_STATIC, CHECK_ON_OTHER_FIELD,
        CEILER_FOR_PERVIOUS, DEFAULT_CONSTRAINT,
        NOT_NULL_FIELD)
values (1, 10, 13, 10, 50, 'Not default value', 'Not null');

insert into CONSTRAINT_ON_OLD_SCHEMA.BASE_TABLE(
        PRIMARY_KEY, UNIQUE_CONSTRAINT,
        CHECK_ON_STATIC, CHECK_ON_OTHER_FIELD,
        CEILER_FOR_PERVIOUS,
        NOT_NULL_FIELD)
values (2, 20, 15, 4, 7, 'Not null');

insert into CONSTRAINT_ON_OLD_SCHEMA.BASE_TABLE(
        PRIMARY_KEY, UNIQUE_CONSTRAINT,
        CHECK_ON_STATIC, CHECK_ON_OTHER_FIELD,
        CEILER_FOR_PERVIOUS, DEFAULT_CONSTRAINT,
        NOT_NULL_FIELD)
values (3, 30, 99, 49, 50, 'Not default value 2', 'Not null 3');

commit;